name: check changelog

on:
  pull_request:
    branches:
      - master

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“– Verify changelog updates
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            CHANGELOG.md
      - name: ðŸ“– Check if changelog was updated
      	if: steps.changed_files.outputs.files_changed == 'false'
        run: |
          exit 1

